{
 "title": "INGESTION LOGS",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Inserted rows volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "electricity",
     "rawSql": "SELECT inserted_at, COUNT() AS \"n inserted rows\" FROM measurements WHERE $__timeFilter(inserted_at) GROUP BY inserted_at ORDER BY inserted_at"
    }
   ]
  },
  {
   "title": "Data overview",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "electricity",
     "rawSql": "SELECT ts,\nmaxIf(value, metric = 'consommation') AS consommation,\nmaxIf(value, metric = 'prevision_j') AS prevision_j,\nmaxIf(value, metric = 'prevision_j1') AS prevision_j1\nFROM measurements\nWHERE value IS NOT NULL\nGROUP BY ts\nORDER BY ts DESC\nLIMIT 1000"
    }
   ]
  },
  {
   "title": "ingest logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"/ds_ingest\"} |= ``"
    }
   ]
  }
 ]
}